
services:
  mongo:
    image: mongo:8.2.2
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: quizzes
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: quizzes
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
  quizzes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://quizzes:password@mongo:27017/quizzes?authSource=admin"
    restart: unless-stopped
