
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quizzes-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      POSTGRESQL_URL: jdbc:postgresql://db:5432/quizzes
      POSTGRESQL_USERNAME: quizzes_user
      POSTGRESQL_PASSWORD: quizzes_pass

      # üîê JWT token (—Å–µ–∫—Ä–µ—Ç)
      JWT_TOKEN: "super_secret_jwt_token"

      # ‚öôÔ∏è JVM tuning
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - ./backend-volume:/app
